[tools]
node = "latest"
"npm:secretlint" = "latest"
"npm:@secretlint/secretlint-rule-preset-recommend" = "latest"
"npm:@antfu/ni" = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
glow = "latest"
lefthook = "latest"
